// frontend/src/App.vue
<script setup>
import { onMounted } from 'vue'
// import { FrappeProvider } from 'frappe-ui'
// import { useTheme } from './hooks/useTheme'
// import { AppProvider } from './context/AppProvider.vue'
// import Dashboard from './components/Dashboard.vue';
// import { Toaster } from '@/components/ui/sonner';
// import ThemeProvider from '@/components/ThemeProvider.vue';
// import ErrorBoundary from './components/ErrorBoundary.vue';

// import { CrossIcon, InfoIcon } from 'lucide-vue-next'
// const theme = useTheme()

// const siteName = import.meta.env.VITE_SITE_NAME
// const socketPort = import.meta.env.VITE_SOCKET_PORT

onMounted(() => {
  // console.log('theme', theme)
  console.log('test')
})
</script>

<template>
  <!-- <FrappeProvider :site-name="siteName" :socket-port="socketPort"> -->
  <!-- <ErrorBoundary> -->
  <!-- <template #fallback>
    <p>Oops! Something broke.</p>
  </template> -->
  <!-- <ThemeProvider default-theme="dark" storage-key="vite-ui-theme"> -->
  <!-- <AppProvider> -->
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900">
    <main class="container mx-auto px-4 dark:bg-gray-900">
      <!-- <Dashboard /> -->
      test
    </main>
    <!-- <Toaster
              rich-colors
              position="bottom-right"
              :icons="{
                success: h(InfoIcon),
                error: h(CrossIcon),
              }"
            /> -->
  </div>
  <!-- </AppProvider> -->
  <!-- </ThemeProvider> -->
  <!-- </ErrorBoundary> -->
  <!-- </FrappeProvider> -->
</template>

// thai_translation_dashboard/src/App.tsx
import React from 'react';
import { FrappeProvider } from 'frappe-react-sdk';

import { AppProvider } from './context/AppProvider';
import Dashboard from './components/Dashboard';
import { Toaster } from '@/components/ui/sonner';
import { useTheme } from './hooks/useTheme';
import { ThemeProvider } from '@/components/ThemeProvider';
import { ErrorBoundary } from './components/ErrorBoundary';
import { CrossIcon, InfoIcon } from 'lucide-react';

const App: React.FC = () => {
  const theme = useTheme();
  console.log('theme', theme);
  return (
    <FrappeProvider
      siteName={import.meta.env.VITE_SITE_NAME}
      socketPort={import.meta.env.VITE_SOCKET_PORT}
    >
      <ErrorBoundary fallback={<p>Opps! Something broke.</p>}>
        <ThemeProvider defaultTheme="dark" storageKey="vite-ui-theme">
          <AppProvider>
            <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
              <main className="container mx-auto px-4 dark:bg-gray-900">
                <Dashboard />
              </main>
              <Toaster
                richColors
                position="bottom-right"
                icons={{
                  success: <InfoIcon />,
                  error: <CrossIcon />,
                }}
              />
            </div>
          </AppProvider>
        </ThemeProvider>
      </ErrorBoundary>
    </FrappeProvider>
  );
};

export default App;
