// translation_tools/public/js/translation_tools/App.jsx
import * as React from "react";

export function App() {
  const dynamicMessage = React.useState("Hello from App.jsx");
  return (
    <div className="m-4 text-center text-moo-blue">
      <h3>{dynamicMessage}</h3>
      <h4>
        Start editing at translation_tools/public/js/translation_tools/App.jsx
      </h4>
    </div>
  );
}

// translation_tools/public/js/translator/App.vue
<script setup>
import { ref } from 'vue';

// biome-ignore lint/correctness/noUnusedVariables: <explanation>
const dynamicMessage = ref('Hello from App.vue');
</script>
<template>
  <div>
    <h3>{{ dynamicMessage }}</h3>
    <h4>Start editing at translation_tools/public/js/translator/App.vue</h4>
  </div>
</template>
